### ISSUE TITLE
How to render Python string with \n \r and whitespace in HTML

### ISSUE THREAD

**Issue by yeongzhiwei** [yeongzhiwei/issues-tracker#55]
```html
<span style="white-space: pre-wrap">Hello\nworld</span>
```

or use css...

```css
div {
    white-space: pre-wrap;
}
```
