### ISSUE TITLE
Nginx + uwsgi + django in docker-compose

### ISSUE THREAD

**Issue by yeongzhiwei** [yeongzhiwei/issues-tracker#62]
Quite a number of things I learnt setting up nginx, uwsgi & django in docker-compose...

nginx
- `upstream` & `server` directive blocks must be enclosed in `http` block in `/etc/nginx/nginx.conf`. However if they are in a conf file placed in `/etc/nginx/sites-enabled/` perhaps via symlinked from `/etc/nginx/sites-available`, the main `nginx.conf` would have `include` directive to collect and nest these conf files in `http` block.

example of nginx.conf to be mapped to `/etc/nginx/nginx.conf`
```conf
events {
  worker_connections 1024;
}

http {
  upstream django {
    server app:8000;
  
  server {
    listen 80;
    server_name some.domain.com; # or ip address
    charset utf-8;

    location / {
      uwsgi_pass django;
      include uwsgi_params;
    }
  }
}
```

example of docker-compose.yml
```yml
services:
  web:
    image: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
   app:
     // build django app here
```

Reference
- https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/uwsgi/
- https://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html
- https://stackoverflow.com/questions/53454739/nginx-upstream-failure-configuration-file#
